### ISSUE TITLE
when making coal coke it instead makes a barrier block

### ISSUE THREAD

**Issue by CherryPie** [Warhand/Limitless-rebirth-1.18.2#1]
**Describe the bug**
when making coal coke it instead makes a barrier block
**To Reproduce**
Steps to reproduce the behavior: put coal in coke oven

**Expected behavior**
it is supposed to make Coal coke

**Screenshots**

**Modpack version:**
- Release: [e.g. 0.1.3]

**Desktop (please complete the following information):**

**Additional context**

**Comment by Warhand** [comment]
Thanks for this report, can you clarify what modpack version this was in? I assume pre-release 4, but I just want to be sure.

**Comment by CherryPie** [comment]
yeah rocks to richs

**Comment by Warhand** [comment]
I can confirm this is also happening on my end, looking for assistance from the IE devs when it comes to fixing it, once I've figured out a solution I'll release a patch.

**Comment by CherryPie** [comment]
thanks :)

**Comment by Warhand** [comment]
Okay, so it seems like this is a probable crafttweaker issue, and would require a fix on their end, but in the meantime, the problem can be solved by just using the `/reload` command whenever you open up a world, you'll need to do it every time you open up a world, and it can take a few minutes, but it should fix the issue until the CT devs release a patch, and I'm able to implement that patch.

Leaving the issue open until such time as the bug is fully resolved.

**Comment by Warhand** [comment]
Actually, after further testing, the `/reload` fix doesn't work, it only fixed JEI.
This issue is more serious than I previously thought, thank you for bringing it to my attention, I'll put in the extra effort to fix this manually on my end, since I don't have time to wait for CT to fix the issue on theirs.

**Comment by Warhand** [comment]
Scratch my last comment on this issue, it appears it just retains the output for as long as the coal is left in the coke oven, when you use `/reload` and then remove and replace the coal from the coke oven, it fixes the issue.
